### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by thehitechpanky** [crazedsanity/cs-phpxml#6]
<b>Fatal error</b>:  Class 'cs_phpxmlAbstract' not found in <b>/var/www/html/subdomains/skcca/admin/mongodb/cs-phpxml-master/cs_phpxmlParser.class.php</b> on line <b>71</b><br />

**Comment by crazedsanity** [comment]
Unfortunately, you would have to `require` all of the class files individually.

**Comment by crazedsanity** [comment]
I've released v`1.2.0`, which supports auto-loading via composer: if you `require` it using composer, then `require_once('vendor/autoload.php');` (adjusting the path as necessary), you should be good to go!
